import { Game, POWER_NAMES } from './game.mjs';
const $=id=>document.getElementById(id), game=new Game(), canvas=$('world'),ctx=canvas.getContext('2d');
const defaults={best:0,wallet:0,runs:0,upgrade:0,character:0,owned:[0],daily:''};
let profile={...defaults},storageOK=true;
try{const saved=JSON.parse(localStorage.getItem('lumen-rush-browser-v1'));if(saved&&typeof saved==='object'){for(const k of ['best','wallet','runs','upgrade','character'])if(Number.isSafeInteger(saved[k])&&saved[k]>=0)profile[k]=saved[k];profile.upgrade=Math.min(5,profile.upgrade);profile.character=Math.min(2,profile.character);if(Array.isArray(saved.owned))profile.owned=[0,...saved.owned.filter(x=>x===1||x===2)];if(typeof saved.daily==='string')profile.daily=saved.daily;}}catch{storageOK=false;}
function save(){try{localStorage.setItem('lumen-rush-browser-v1',JSON.stringify(profile));}catch{storageOK=false;toast('Storage unavailable. Progress lasts for this session.');}}
function bank(){if(game.banked||game.distance<=0)return;game.banked=true;profile.best=Math.max(profile.best,game.score);profile.wallet+=game.coins;profile.runs++;save();}
let w=0,h=0,time=0,last=0,menuTravel=0,toastUntil=0,sound=false,audio;
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastUntil=performance.now()+2600;}
function tone(freq=700,duration=.08){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=freq;osc.type='sine';gain.gain.setValueAtTime(.055,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);}catch{sound=false;}}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'SOUND ON':'SOUND OFF';tone();};
function button(text,action,primary=false){const b=document.createElement('button');b.className='wide'+(primary?' primary':'');b.textContent=text;b.onclick=()=>{tone(500);action();};$('panel').append(b);return b;}
function page(html){$('overlay').hidden=false;$('hud').hidden=true;$('touch').hidden=true;$('panel').innerHTML=html;}
function home(){game.state='menu';page(`<div class="eyebrow">THE CITY SLEEPS. YOU DON'T.</div><h1>OWN THE<br><span>NIGHT.</span></h1><p>One courier. Three lanes. An endless neon city.<br>Find your rhythm on the Afterlight line.</p><div class="record"><div><small>PERSONAL BEST</small><strong>${profile.best.toLocaleString()}</strong></div><div><small>YOUR TOKENS</small><strong>◈ ${profile.wallet.toLocaleString()}</strong></div></div>`);button('START A RUN                                       ↗',start,true);const row=document.createElement('div');row.className='row';$('panel').append(row);for(const [text,fn] of [['COURIERS',characters],['UPGRADES',shop],['DAILY DROP',daily]]){const b=document.createElement('button');b.textContent=text;b.onclick=fn;row.append(b);}const p=document.createElement('p');p.className='note';p.textContent=storageOK?'NO DOWNLOAD. JUST ONE MORE RUN.':'Storage unavailable · progress stays in this session';$('panel').append(p);}
function start(){game.start(profile.upgrade);showRun();toast('Follow tokens. Orange: jump. Gates: slide. Cargo: dodge.');}
function showRun(){$('overlay').hidden=true;$('hud').hidden=false;$('touch').hidden=false;}
function pausePage(){page('<div class="eyebrow">TAKE A BREATHER</div><h2>RUN PAUSED.</h2><p>Your route will be right here.</p>');button('RESUME →',()=>{game.action('pause');showRun();},true);button('RESTART',()=>{bank();start();});button('FINISH & RETURN HOME',()=>{bank();home();});}
function gameOver(){page(`<div class="eyebrow">ROUTE COMPLETE</div><h2>NICE RUN.</h2><div class="record"><div><small>RUN SCORE</small><strong>${game.score.toLocaleString()}</strong></div><div><small>DISTANCE</small><strong>${Math.floor(game.distance)} m</strong></div></div><p>◈ ${game.coins} tokens collected${game.score>profile.best?' · New personal best!':''}</p>`);if(!game.revived)button('SECOND WIND · FREE REVIVE ↗',()=>{game.revive();showRun();},true);button('RUN AGAIN',()=>{bank();start();},game.revived);button('COLLECT & RETURN HOME',()=>{bank();home();});}
function characters(){page(`<div class="eyebrow">COURIER COLLECTIVE</div><h2>FIND YOUR STYLE.</h2><p>◈ ${profile.wallet} tokens<br>Every courier has the same abilities.</p>`);['ARIA / Tide','NIKO / Ember','SOL / Ultraviolet'].forEach((name,id)=>{button(name+(profile.character===id?' · EQUIPPED':profile.owned.includes(id)?' · EQUIP':` · ${id*400} tokens`),()=>{if(!profile.owned.includes(id)){if(profile.wallet<id*400){toast('Keep running to earn more tokens.');return;}profile.wallet-=id*400;profile.owned.push(id);}profile.character=id;save();characters();},profile.character===id);});button('← BACK',home);}
function shop(){page(`<div class="eyebrow">THE EXCHANGE</div><h2>GO A LITTLE LONGER.</h2><p>◈ ${profile.wallet} tokens<br>Extend all nine power-ups by one second per level.<br>Current duration: ${8+profile.upgrade}s · Level ${profile.upgrade}/5</p>`);const b=button(profile.upgrade>=5?'MAXIMUM LEVEL':`UPGRADE · ${150*(profile.upgrade+1)} tokens`,()=>{const cost=150*(profile.upgrade+1);if(profile.wallet<cost){toast('Not enough tokens yet.');return;}if(profile.upgrade>=5)return;profile.wallet-=cost;profile.upgrade++;save();shop();},true);b.disabled=profile.upgrade>=5;button('← BACK',home);}
function daily(){const today=new Date().toISOString().slice(0,10);if(profile.daily>=today){toast('Drop collected. Next delivery at 00:00 UTC.');return;}profile.wallet+=100;profile.daily=today;save();home();toast('Daily delivery: +100 tokens.');}
function action(name){const before=game.state;game.action(name);if(before!==game.state){if(game.state==='paused')pausePage();else if(game.state==='running')showRun();}}
$('pause').onclick=()=>action('pause');
const keys={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'jump',' ':'jump',w:'jump',ArrowDown:'slide',s:'slide',S:'slide',Escape:'pause',p:'pause',P:'pause'};
window.addEventListener('keydown',e=>{if(!keys[e.key]||e.repeat)return;if(e.target instanceof HTMLButtonElement && (e.key===' '||e.key==='Enter'))return;e.preventDefault();action(keys[e.key]);});
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action);}));
let swipe=null;canvas.addEventListener('pointerdown',e=>{swipe={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});
function swipeMove(e){if(!swipe)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;if(Math.hypot(dx,dy)<Math.max(24,w*.035))return;action(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'slide':'jump');swipe=null;}
canvas.addEventListener('pointermove',swipeMove);canvas.addEventListener('pointerup',e=>{swipeMove(e);swipe=null;});canvas.addEventListener('pointercancel',()=>swipe=null);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.state==='running')action('pause');});window.addEventListener('blur',()=>{if(game.state==='running')action('pause');});window.addEventListener('pagehide',bank);
function resize(){w=window.innerWidth;h=$('game').clientHeight;const dpr=Math.min(2,devicePixelRatio||1);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}window.addEventListener('resize',resize);resize();
// Perspective camera: runner at z=0, camera eight meters behind and four meters up.
function project(x,y,z){const f=Math.min(w*1.08,h*.96),scale=f/(z+8);return{x:w*.5+(x-game.x*.11)*scale,y:h*.37+(4-y)*scale,s:scale};}
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();}
function box(x,y,z,bw,bh,bd,color,side='#133b49',top='#30727c'){if(z-bd/2<=-7)return;const a=project(x-bw/2,y,z-bd/2),b=project(x+bw/2,y,z-bd/2),c=project(x+bw/2,y+bh,z-bd/2),d=project(x-bw/2,y+bh,z-bd/2),e=project(x-bw/2,y+bh,z+bd/2),f=project(x+bw/2,y+bh,z+bd/2),g=project(x+bw/2,y,z+bd/2);poly([a,b,c,d],color);poly([d,c,f,e],top);if(x<0)poly([b,g,f,c],side);else poly([a,project(x-bw/2,y,z+bd/2),e,d],side);}
function line(a,b,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}
function token(x,z){const p=project(x,1.1+Math.sin(time*3+z)*.12,z);ctx.save();ctx.shadowColor='#ffc66a';ctx.shadowBlur=12;ctx.fillStyle='#ffce70';ctx.beginPath();ctx.ellipse(p.x,p.y,Math.max(1,p.s*.21*Math.abs(Math.cos(time*2+z))),p.s*.29,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.restore();}
function render(){const travel=game.state==='menu'?menuTravel:game.distance;const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#06111f');sky.addColorStop(.48,'#234653');sky.addColorStop(1,'#0a1b2a');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
 ctx.fillStyle='#9ac6c7';ctx.globalAlpha=.4;ctx.beginPath();ctx.arc(w*.72,h*.18,26,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;
 for(let i=0;i<40;i++){const x=((i*239+19)%1000)/1000*w,y=((i*71)%230)/1000*h;ctx.fillStyle='#99c8d54a';ctx.fillRect(x,y,1.3,1.3);}
 for(let i=0;i<25;i++){const x=i*w/24,bh=20+(i*37%85);ctx.fillStyle=i%2?'#132b3b':'#193443';ctx.fillRect(x,h*.37-bh,w/23,bh);}
 poly([project(-4.4,0,-6),project(4.4,0,-6),project(4.4,0,260),project(-4.4,0,260)],'#10212b');
 for(let z=240;z>-6;z-=6){const zz=z-travel%6;for(const x of [-1.35,1.35])poly([project(x-.025,.015,zz),project(x+.025,.015,zz),project(x+.025,.015,zz+2.5),project(x-.025,.015,zz+2.5)],'#65858b88');}
 for(const x of [-4.5,4.5]){line(project(x,.03,-6),project(x,.03,260),'#43e6c4',3);line(project(x*1.06,.03,-6),project(x*1.06,.03,260),'#1a6770',8);}
 for(let i=16;i>=0;i--){const z=i*16-travel%16; if(z<0)continue;for(const side of [-1,1]){const n=i+Math.floor(travel/16),height=9+(n*17%19),x=side*(8+(n%3));box(x,0,z,4.5,height,11,'#102333','#0b1929','#203847');for(let y=3;y<height;y+=3){const nearX=x-side*2.3;line(project(nearX,y,z-4.7),project(nearX,y,z+4.7),n%3?'#2d8c9688':'#9664c588',Math.max(1,project(x,y,z).s*.11));}box(side*4.8,0,z,.09,5.5,.09,'#265162');box(side*4.35,5.5,z,1.1,.09,.15,'#8fffe0','#5ae6c3','#c9fff1');}}
 const items=game.state==='menu'?Array.from({length:16},(_,i)=>({kind:i%6===5?'barrier':'coin',lane:i%3-1,z:20+i*7+travel})):game.items;
 for(const item of [...items].sort((a,b)=>b.z-a.z)){const z=item.z-travel;if(item.done||z<-4||z>220)continue;ctx.globalAlpha=Math.max(.08,Math.min(1,(230-z)/110));const x=item.lane*2.7;
  if(item.kind==='coin')token(x,z);
  if(item.kind==='power'){box(x,.8+Math.sin(time*3)*.2,z,.65,.65,.65,'#77ffe0','#278caa','#d8fff1');const p=project(x,2,z);ctx.fillStyle='#b1ffdf';ctx.font=`bold ${Math.max(9,p.s*.2)}px monospace`;ctx.textAlign='center';if(z<45)ctx.fillText(POWER_NAMES[item.power].toUpperCase(),p.x,p.y);}
  if(item.kind==='barrier'){box(x,0,z,2,1.1,.65,'#d16a36','#88452f','#f49b54');for(let j=-2;j<=2;j++)box(x+j*.36,.18,z-.35,.15,.74,.03,'#ffcf79','#b18556','#ffcf79');}
  if(item.kind==='pipe')box(x,0,z,2,.64,.7,'#9569bf','#563e7c','#bc8ad8');
  if(item.kind==='gate'){for(const dx of [-.95,.95])box(x+dx,0,z,.13,3,.25,'#4ec4bc');box(x,1.1,z,2.1,1.8,.45,'#d68c44','#98572d','#ffb767');const p=project(x,2.05,z-.25);ctx.fillStyle='#202b31';ctx.font=`bold ${Math.max(8,p.s*.3)}px monospace`;ctx.textAlign='center';ctx.fillText('↓ SLIDE',p.x,p.y);}
  if(item.kind==='cargo'){box(x,0,z,2.1,3.2,2,'#254853','#163341','#3f6971');for(let j=-2;j<=2;j++)box(x+j*.4,.1,z-1.02,.06,3,.04,'#51b9b1');}
  if(item.kind==='vehicle'){box(x,0,z,1.9,2.4,5,'#288e94','#185963','#48b3b0');box(x,1.3,z-2.52,1.55,.8,.035,'#102e43');for(const dx of [-.66,.66])box(x+dx,.45,z-2.55,.32,.14,.03,'#ff9367');}
 }ctx.globalAlpha=1;
 const x=game.state==='menu'?0:game.x,y=game.state==='menu'?0:game.height,sliding=game.slide>0&&game.state!=='menu',active=game.state==='running'||game.state==='menu',stride=active?Math.sin(time*game.speed*.8)*.3:0;
 const foot=project(x,0,0);ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(foot.x,foot.y,foot.s*.55,foot.s*.16,0,0,Math.PI*2);ctx.fill();
 if(game.immunity>0&&game.state==='running')ctx.globalAlpha=.7+.3*Math.sin(time*22);
 const jacket=['#50d9c2','#ef9752','#b28aee'][profile.character];
 if(sliding){box(x,y+.15,0,.72,.48,1.05,jacket,'#276978','#8debdc');box(x,y+.35,.5,.48,.45,.48,'#233649','#112230','#476071');}
 else{box(x-.19,y+.05,Math.max(-.3,stride),.23,.73,.26,'#21314a','#142338','#3b5061');box(x+.19,y+.05,-stride,.23,.73,.26,'#21314a','#142338','#3b5061');box(x,y+.77,0,.65,.78,.4,jacket,'#277d7c','#99f4db');box(x,y+.91,-.29,.48,.58,.22,'#172b40','#0e1d32','#34546a');box(x,y+1.56,0,.48,.48,.48,'#263c51','#162638','#4f6c7e');box(x,y+1.63,-.25,.38,.07,.03,'#71ffe0');box(x-.43,y+.77,stride*.7,.18,.64,.2,jacket);box(x+.43,y+.77,-stride*.7,.18,.64,.2,jacket);}
 ctx.globalAlpha=1;
 if(game.powers[2]>0||game.powers[6]>0||game.powers[8]>0){const p=project(x,y+1,0);ctx.strokeStyle='#77f8dc';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y,p.s*.7,p.s*1.22,0,0,Math.PI*2);ctx.stroke();}
 const shade=ctx.createLinearGradient(0,0,0,h);shade.addColorStop(0,'#05101999');shade.addColorStop(.25,'#05101900');shade.addColorStop(.85,'#05101900');shade.addColorStop(1,'#051019aa');ctx.fillStyle=shade;ctx.fillRect(0,0,w,h);
}
function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(game.state==='running'||game.state==='menu')time+=dt;if(game.state==='menu')menuTravel+=dt*5;const before=game.state;game.tick(dt);if(before==='running'&&game.state==='over')gameOver();for(const e of game.events.splice(0)){if(e==='coin')tone(1050,.055);else if(e==='jump')tone(420,.12);else if(e==='crash')tone(65,.25);else toast(e);}if(now>toastUntil)$('toast').classList.remove('visible');$('score').textContent=game.score.toLocaleString();$('coins').textContent=game.coins;$('distance').textContent=Math.floor(game.distance);$('powers').textContent=(game.chase>.1?'PATROL CLOSE\n':'')+Object.entries(game.powers).map(([id,t])=>`${POWER_NAMES[id].toUpperCase()}  ${t.toFixed(1)}s`).join('\n');render();requestAnimationFrame(frame);}
home();requestAnimationFrame(frame);
