import test from 'node:test';
import assert from 'node:assert/strict';
import { Game, safeLane } from './game.mjs';
function run(g,seconds){for(let t=0;t<seconds;t+=.01)g.tick(.01);}
test('every generated obstacle row leaves a token lane clear',()=>{for(let seed=0;seed<100;seed++){const g=new Game(()=>seed/100);g.start();for(let row=0;row<g.row;row++){const safe=safeLane(g.seed,row),z=42+row*18;assert.ok(safe>=-1&&safe<=1);assert.equal(g.items.filter(i=>i.z===z&&i.kind!=='coin'&&i.kind!=='power').length,2);assert.ok(!g.items.some(i=>i.z===z&&i.lane===safe&&i.kind!=='coin'));}}});
test('lane clamps, jump lands, slide expires, pause freezes simulation',()=>{const g=new Game();g.start();g.action('right');g.action('right');run(g,.3);assert.ok(g.x>2.5&&g.x<=2.7);g.action('jump');run(g,.2);assert.ok(g.height>1);g.action('pause');const snapshot=JSON.stringify(g);run(g,1);assert.equal(JSON.stringify(g),snapshot);g.action('pause');g.action('slide');run(g,1);assert.equal(g.height,0);assert.equal(g.slide,0);});
test('collision, single revive, and restart clear run state',()=>{const g=new Game();g.start();g.immunity=0;g.items=[{kind:'cargo',lane:0,z:.9}];run(g,.1);assert.equal(g.state,'over');g.revive();assert.equal(g.state,'running');assert.equal(g.revived,true);g.immunity=0;g.hit(true);g.revive();assert.equal(g.state,'over');g.start();assert.equal(g.score,0);assert.equal(g.revived,false);});
test('jump clears barriers and a grounded slide clears gates',()=>{for(const kind of ['barrier','gate']){const g=new Game();g.start();g.immunity=0;g.items=[];g.action(kind==='barrier'?'jump':'slide');run(g,.2);g.items=[{kind,lane:0,z:g.distance+.8}];run(g,.1);assert.equal(g.state,'running');}});
test('airborne slide does not pass through gate',()=>{const g=new Game();g.start();g.immunity=0;g.height=2;g.slide=.8;g.items=[{kind:'gate',lane:0,z:.8}];g.tick(.02);assert.equal(g.state,'over');});
test('shield is consumed, powers expire, booster score never decreases',()=>{const g=new Game();g.start();g.immunity=0;g.powers[2]=8;g.hit(true);assert.equal(g.state,'running');assert.equal(g.powers[2],undefined);g.powers[1]=.1;g.items=[];run(g,.09);const score=g.score;run(g,.2);assert.ok(g.score>=score);assert.equal(g.powers[1],undefined);});
test('tokens collect once and double-token power applies',()=>{const g=new Game();g.start();g.items=[{kind:'coin',lane:0,z:.6}];g.powers[4]=8;run(g,.2);assert.equal(g.coins,2);});
test('long run keeps generation bounded',()=>{const g=new Game();g.start();for(let i=0;i<20000;i++){g.immunity=1;g.tick(.05);}assert.equal(g.state,'running');assert.ok(g.distance>20000);assert.ok(g.items.length<150);});
